### ISSUE TITLE
Much digits in output

### ISSUE THREAD

**Issue by Gaucer** [natemara/python-erlang#1]
Hi
`print(erlang.extended_b_lines(5.12, 0.01))`
returns very much digits and correct answer at the end
// just little part

> 2.4415009320594105
> 3.3729458264025767
> 4.933883923456585
> 7.713482986854191
> 12.995032740941861
> 23.734259464332833
> 47.13564647803623
> 1.1943532319112715
> 1.464252821331256
> 1.8537468044827816
> 2.4411267303856823
> 3.3722043477772625
> 4.932392881934515
> 7.710385483620866
> 12.98830670418774
> 23.718874465123502
> 47.09839909594484
> 11

how it can be fixed?

**Comment by lily-mara** [comment]
Hi, thanks for submitting this issue! I didn't realize it, but I left an extra `print` call in there. If you re-clone the repository, or run `$ pip -U python-erlang`, that should fix it.

**Comment by Gaucer** [comment]
Thank you :)
